apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${{ values.serviceName }}
  labels:
    bridges.triggermesh.io/id: ${{ values.name }}
spec:
  template:
    spec:
      containers:
        - image: ${{ values.serviceImage }}
